### ISSUE TITLE
Release users' "Display name" value as one of the LDAP attributes

### ISSUE THREAD

**Issue by andmor-** [clarin-eric/unity-ldap#3]
In our previous LDAP, the users' display name was being released as a different field from the users' email address. This field was typically filed in with the users' real name e.g. "John Smith" and then provisioned, by the Drupal LDAP filter, to the Drupal user database itself as the users' "display name" property.
Some Drupal modules then use the Drupal "display name" property for authorization purposes and since the new LDAP only releases the email address value in all its attributes, the match is impossible to keep.
This is currently causing users to lose permissions or ownership of their content.

**Comment by WillemElbers** [comment]
Added in:
* https://github.com/clarin-eric/unity-ldap/commit/67658ee4cd407c1cadfeeb3676a0718ec72f68bd
* https://github.com/clarin-eric/unity-ldap/commit/68ef01e2abe99a0df9432e0391f8355bbea9efdf
