### ISSUE TITLE
Investigate why is "dn" always requested as shown is the unity LDAP logs?

### ISSUE THREAD

**Issue by andmor-** [clarin-eric/unity-ldap#4]
When I login with any user on the www.clarin.eu website I see the following warning on unity logs:

`2017-08-03 12:08:57,326 [pool-5-thread-2] WARN  org.apache.directory.server.core.api.interceptor.context.FilteringOperationContext  - Requested attribute dn does not exist in the schema, it will be ignored`

Since we are not requesting 'dn' as an attribute it is unclear why is this warning being raised.
We should investigate the possibility of this being the indication of a problem.

**Comment by WillemElbers** [comment]
Edited: ```schema/ou=schema/cn=system/ou=attributetypes/m-oid=2.5.4.49.ldif``` to add ```m-name: dn```

**Comment by WillemElbers** [comment]
This seems to have fixed the issue, closing for now.
